# ─── Stage 1: Dependencies ───
FROM node:20-alpine3.21  AS builder
RUN npm install -g pnpm@9
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml .npmrc ./
COPY apps/web/package.json ./apps/web/
RUN pnpm install --frozen-lockfile

# ─── Stage 2: Production ───
FROM node:20-alpine3.21 AS production
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/web/node_modules ./apps/web/node_modules
COPY apps/web/ ./apps/web/
COPY package.json pnpm-workspace.yaml ./
EXPOSE 4000
CMD ["node", "apps/web/app.js"]
